---
- name: Read device information
  tchevalleraud.extremenetworks_xiqse.device_read:
    ip_address: "{{ ip_address }}"
    provider:
      host: "{{ xiqse_host }}"
      client_id: "{{ xiqse_client }}"
      client_secret: "{{ xiqse_secret }}"
      port: "{{ xiqse_port }}"
      protocol: "{{ xiqse_protocol }}"
      verify: "{{ xiqse_verify }}"

- name: Allow time for XIQ-SE to finish synchronizing
  ansible.builtin.wait_for:
    timeout: 10