all:
  children:
    voss_devices:
      vVOSS1:
        ansible_host: 10.0.0.11
      vVOSS2:
        ansible_host: 10.0.0.12
    xiqse_servers:
      hosts:
        xiqse:
          ansible_host: 10.0.0.254
        xiqse_api:
          ansible_connection: local
          ansible_host: localhost