name: Publish Collection to Ansible Galaxy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetech-depth: 0
      
      - name: Fetch all tags
        run: git fetch --tags

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'

#      - name: Install Ansible and dependencies
#        run: |
#          pip install ansible ansible-lint

      - name: Get last tag or fallback
        id: lasttag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Get commits since last tag
        id: commits
        run: |
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            last_tag=$(git describe --tags --abbrev=0)
            range="$last_tag..HEAD"
          else
            last_tag=""
            range="HEAD"
          fi
      
          echo "tag=$last_tag" >> $GITHUB_OUTPUT
          commits=$(git log $range --pretty=format:"%s")
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$commits" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine version bump from hashtags
        id: bump
        run: |
          bump="patch"
          echo "${{ steps.commits.outputs.commits }}" | grep -qi '#major' && bump="major"
          echo "${{ steps.commits.outputs.commits }}" | grep -qi '#minor' && bump="minor"
          echo "bump=$bump" >> $GITHUB_OUTPUT

      - name: Calculate new version
        id: newversion
        run: |
          old="${{ steps.commits.outputs.tag }}"
          [ -z "$old" ] && old="v0.0.0"
          echo "🔍 Last tag: $old"
          old=${old#v}
          IFS='.' read -r major minor patch <<< "$old"
          case "${{ steps.bump.outputs.bump }}" in
            major) major=$((major+1)); minor=0; patch=0 ;;
            minor) minor=$((minor+1)); patch=0 ;;
            patch) patch=$((patch+1)) ;;
          esac
          new="v$major.$minor.$patch"
          echo "new=$new" >> $GITHUB_OUTPUT

      - name: Show new version
        run: |
          echo "🔖 New version will be ${{ steps.commits.outputs.tag }}"

      - name: Replace version in README.md and Galaxy.yml
        uses: richardrigutins/replace-in-files@v2
        with:
          files: |
            README.md
            galaxy.yml
          search: '${{ steps.commits.outputs.tag }}'
          replace: '${{ steps.newversion.outputs.new }}'

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

      - name: Create new tag
        run: |
          git tag ${{ steps.newversion.outputs.new }}
          git push origin ${{ steps.newversion.outputs.new }}

#      - name: Build Ansible Collection
#        run: |
#          ansible-galaxy collection build --output-path ./dist

#      - name: Publish Collection
#        env:
#          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
#        run: |
#          ansible-galaxy collection publish dist/*.tar.gz --api-key "$ANSIBLE_GALAXY_API_KEY"