name: Publish Collection to Ansible Galaxy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and dependencies
        run: |
          pip install ansible ansible-lint

      - name: Replace single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          search-text: 'x.x.x'
          replacement-text: '1.0.0'

#      - name: Build Ansible Collection
#        run: |
#          ansible-galaxy collection build --output-path ./dist

#      - name: Publish Collection
#        env:
#          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
#        run: |
#          ansible-galaxy collection publish dist/*.tar.gz --api-key "$ANSIBLE_GALAXY_API_KEY"